"""Advertisement dissection (G-7.5).

Parse BlueZ-exposed advertisement blobs — ``ManufacturerData``,
``ServiceData``, advertised service UUIDs, and ``AdvertisingData`` — into
structured, attributed fields.

Design goals:
    * **Lossless** — every entry keeps its raw hex *and* a printable-ASCII
      rendering. Advertisements sometimes carry clear text (e.g. some
      Bluetooth headsets embed a model/name), so no captured byte is dropped.
    * **Two-source attribution** — Bluetooth SIG assigned numbers
      (``bt_ref.uuids`` via the shared resolvers) *plus* vendor/community
      fingerprints (``bt_ref.vendor_adv_specs``, generated by
      ``update_vendor_specs``).
    * **Graceful** — a protocol decoder failure never discards the raw entry.

The dissector is pure and side-effect free; callers decide whether to persist
or render the result.  See ``docs/adv_dissection.md``.
"""
from __future__ import annotations

import json as _json
from typing import Any, Dict, List, Mapping, Optional

from bleep.bt_ref.constants import (
    BT_SIG_BASE_UUID_SUFFIX,
    COMPANY_ID__APPLE,
    SERVICE_DATA_PROTOCOL_LABELS,
)
from bleep.ble_ops.common.conversion import _resolve_ad_type_name, _resolve_company_name

# Curated service-data/beacon labels are centralised in ``bt_ref.constants`` (the
# canonical UUID reference layer) and re-exported here for callers/tests. The
# classifier imports the same source, so the two cannot drift. See
# docs/adv_dissection.md ("Known UUID attribution corrections").
__all__ = [
    "SERVICE_DATA_PROTOCOL_LABELS",
    "dissect_advertisement",
    "dissect_persisted_record",
    "format_beacon_summary",
]

_SIG_SUFFIX = BT_SIG_BASE_UUID_SUFFIX.lower()

# Apple Continuity TLV message types (device-library apple_dispatcher).
_APPLE_CONTINUITY_TYPES: Dict[int, str] = {
    0x02: "ibeacon",
    0x05: "airdrop",
    0x06: "homekit",
    0x07: "proximity_pairing",
    0x08: "hey_siri",
    0x09: "airplay_target",
    0x0A: "airplay_source",
    0x0B: "magic_switch",
    0x0C: "handoff",
    0x0D: "tethering_target",
    0x0E: "tethering_source",
    0x0F: "nearby_action",
    0x10: "nearby_info",
    0x12: "find_my",
}

# Eddystone URL scheme prefixes and expansion codes (device-library eddystone).
_EDDYSTONE_SCHEMES = ["http://www.", "https://www.", "http://", "https://"]
_EDDYSTONE_EXPANSIONS = [
    ".com/", ".org/", ".edu/", ".net/", ".info/", ".biz/", ".gov/",
    ".com", ".org", ".edu", ".net", ".info", ".biz", ".gov",
]


def _to_bytes(value: Any) -> bytes:
    """Best-effort coerce a D-Bus byte array / list / bytes to ``bytes``."""
    if value is None:
        return b""
    if isinstance(value, (bytes, bytearray)):
        return bytes(value)
    try:
        return bytes(int(b) & 0xFF for b in value)
    except (TypeError, ValueError):
        return b""


def _ascii(raw: bytes) -> str:
    """Printable-ASCII rendering; non-printable bytes → U+FFFD (lossless pair)."""
    return "".join(chr(b) if 0x20 <= b <= 0x7E else "\ufffd" for b in raw)


def _uuid16_of(uuid: str) -> Optional[str]:
    """Return the 16-bit form (lower-case, 4 hex) of a UUID string, if derivable."""
    s = str(uuid).strip().lower()
    if len(s) == 4:
        return s
    # 128-bit BT SIG base UUID: 0000XXXX + BT_SIG_BASE_UUID_SUFFIX
    if len(s) >= 8 and s[8:] == _SIG_SUFFIX:
        return s[4:8]
    return None


def _vendor_specs():
    try:
        from bleep.bt_ref import vendor_adv_specs as _specs
        return _specs
    except Exception:  # noqa: BLE001 - reference module always committed, be safe
        return None


def _sig_uuid_name(uuid: str) -> Optional[str]:
    try:
        from bleep.bt_ref.utils import get_name_from_uuid
        name = get_name_from_uuid(uuid)
        return name if name and name != "Unknown" else None
    except Exception:  # noqa: BLE001
        return None


# ---------------------------------------------------------------------------
# Protocol decoders
# ---------------------------------------------------------------------------

def _decode_ibeacon(payload: bytes) -> Optional[Dict[str, Any]]:
    """Decode an iBeacon payload (0x02 0x15 <uuid16> <major> <minor> <tx>)."""
    if len(payload) < 23 or payload[0] != 0x02 or payload[1] != 0x15:
        return None
    return {
        "protocol": "ibeacon",
        "uuid": payload[2:18].hex(),
        "major": int.from_bytes(payload[18:20], "big"),
        "minor": int.from_bytes(payload[20:22], "big"),
        "tx_power": int.from_bytes(payload[22:23], "big", signed=True),
    }


# Compact Espressif-observed framing: CID 0xFFFF + exactly 5 bytes.
_IBEACON_COMPACT_CIDS = frozenset({0xFFFF})


def _decode_ibeacon_compact(payload: bytes) -> Optional[Dict[str, Any]]:
    """Decode allowlisted compact major/minor/tx manufacturer payloads."""
    if len(payload) != 5:
        return None
    return {
        "protocol": "ibeacon_compact",
        "uuid": None,
        "major": int.from_bytes(payload[0:2], "big"),
        "minor": int.from_bytes(payload[2:4], "big"),
        "tx_power": int.from_bytes(payload[4:5], "big", signed=True),
    }


def _decode_apple_continuity(payload: bytes) -> Optional[Dict[str, Any]]:
    """Split Apple Continuity manufacturer payload into TLV messages."""
    messages: List[Dict[str, Any]] = []
    i = 0
    while i + 1 < len(payload):
        msg_type = payload[i]
        length = payload[i + 1]
        data = payload[i + 2 : i + 2 + length]
        entry = {
            "type": f"0x{msg_type:02x}",
            "name": _APPLE_CONTINUITY_TYPES.get(msg_type, "unknown"),
            "raw_hex": data.hex(),
        }
        if msg_type == 0x02:
            ibeacon = _decode_ibeacon(bytes([0x02, len(data)]) + data)
            if ibeacon:
                entry["decoded"] = ibeacon
        messages.append(entry)
        i += 2 + length
    return {"protocol": "apple_continuity", "messages": messages} if messages else None


def _decode_eddystone(payload: bytes) -> Optional[Dict[str, Any]]:
    """Decode an Eddystone service-data frame (UID / URL / TLM / EID)."""
    if not payload:
        return None
    frame = payload[0]
    if frame == 0x00 and len(payload) >= 18:
        return {"protocol": "eddystone", "frame": "uid",
                "namespace": payload[2:12].hex(), "instance": payload[12:18].hex()}
    if frame == 0x10 and len(payload) >= 3:
        scheme = _EDDYSTONE_SCHEMES[payload[2]] if payload[2] < len(_EDDYSTONE_SCHEMES) else ""
        url = scheme
        for b in payload[3:]:
            url += _EDDYSTONE_EXPANSIONS[b] if b < len(_EDDYSTONE_EXPANSIONS) else chr(b) if 0x20 <= b <= 0x7E else ""
        return {"protocol": "eddystone", "frame": "url", "url": url}
    if frame == 0x20 and len(payload) >= 14:
        return {"protocol": "eddystone", "frame": "tlm",
                "battery_mv": int.from_bytes(payload[2:4], "big"),
                "temperature_raw": payload[4:6].hex(),
                "adv_count": int.from_bytes(payload[6:10], "big"),
                "uptime_100ms": int.from_bytes(payload[10:14], "big")}
    if frame == 0x30 and len(payload) >= 10:
        return {"protocol": "eddystone", "frame": "eid", "eid": payload[2:10].hex()}
    return {"protocol": "eddystone", "frame": f"0x{frame:02x}"}


# ---------------------------------------------------------------------------
# Attribution helpers
# ---------------------------------------------------------------------------

def _vendor_hints_company(cid: int, payload: bytes) -> List[str]:
    specs = _vendor_specs()
    if specs is None:
        return []
    key = f"{cid:04x}"
    hints = list(getattr(specs, "COMPANY_ID", {}).get(key, []))
    ph = payload.hex()
    for entry in getattr(specs, "MANUFACTURER_PREFIX", []):
        if entry.get("company_id") == key and ph.startswith(entry.get("prefix", "")):
            if entry["name"] not in hints:
                hints.append(entry["name"])
    return hints


def _vendor_hint_service(table_name: str, key: str) -> Optional[str]:
    specs = _vendor_specs()
    if specs is None:
        return None
    return getattr(specs, table_name, {}).get(key)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def dissect_advertisement(
    manufacturer_data: Optional[Dict[Any, Any]] = None,
    service_data: Optional[Dict[Any, Any]] = None,
    service_uuids: Optional[List[str]] = None,
    advertising_data: Optional[Dict[Any, Any]] = None,
) -> Dict[str, Any]:
    """Dissect advertisement fields into a structured, lossless result.

    All arguments are optional and tolerant of D-Bus wrapper types. The return
    value always contains ``manufacturer_data``, ``service_data``,
    ``service_uuids``, ``advertising_data`` lists and a ``summary`` dict.
    """
    result: Dict[str, Any] = {
        "manufacturer_data": [],
        "service_data": [],
        "service_uuids": [],
        "advertising_data": [],
        "summary": {"vendors": [], "protocols": []},
    }
    vendors: List[str] = []
    protocols: List[str] = []

    for cid_raw, val in (manufacturer_data or {}).items():
        try:
            cid = int(cid_raw)
        except (TypeError, ValueError):
            continue
        raw = _to_bytes(val)
        hints = _vendor_hints_company(cid, raw)
        entry: Dict[str, Any] = {
            "company_id": cid,
            "company_id_hex": f"0x{cid:04x}",
            "company": _resolve_company_name(cid),
            "vendor_hints": hints,
            "raw_hex": raw.hex(),
            "ascii": _ascii(raw),
        }
        decoded = None
        if cid == COMPANY_ID__APPLE:
            decoded = _decode_ibeacon(raw) or _decode_apple_continuity(raw)
        elif len(raw) >= 23 and raw[0] == 0x02 and raw[1] == 0x15:
            decoded = _decode_ibeacon(raw)
        elif cid in _IBEACON_COMPACT_CIDS:
            decoded = _decode_ibeacon_compact(raw)
        if decoded:
            entry["decoded"] = decoded
            protocols.append(decoded["protocol"])
        vendors.extend(hints)
        result["manufacturer_data"].append(entry)

    for uuid_raw, val in (service_data or {}).items():
        raw = _to_bytes(val)
        uuid = str(uuid_raw)
        u16 = _uuid16_of(uuid)
        vendor_hint = _vendor_hint_service("SERVICE_DATA_UUID16", u16) if u16 else None
        protocol_label = SERVICE_DATA_PROTOCOL_LABELS.get(u16) if u16 else None
        entry = {
            "uuid": uuid,
            "uuid_16": u16,
            "name": _sig_uuid_name(uuid),
            "protocol": protocol_label,
            "vendor_hints": [vendor_hint] if vendor_hint else [],
            "raw_hex": raw.hex(),
            "ascii": _ascii(raw),
        }
        if u16 == "feaa":
            decoded = _decode_eddystone(raw)
            if decoded:
                entry["decoded"] = decoded
                protocols.append("eddystone")
        if protocol_label:
            protocols.append(protocol_label)
        if vendor_hint:
            vendors.append(vendor_hint)
        result["service_data"].append(entry)

    feaa_payload_seen = any(
        (e.get("uuid_16") == "feaa" and e.get("decoded"))
        for e in result["service_data"]
    )

    for uuid_raw in (service_uuids or []):
        uuid = str(uuid_raw)
        u16 = _uuid16_of(uuid)
        u128 = uuid.strip().lower().replace("-", "")
        vendor_hint = (
            _vendor_hint_service("SERVICE_UUID16", u16) if u16 else None
        ) or _vendor_hint_service("SERVICE_UUID128", u128)
        entry = {"uuid": uuid, "uuid_16": u16, "name": _sig_uuid_name(uuid),
                 "vendor_hints": [vendor_hint] if vendor_hint else []}
        if u16 == "feaa" and not feaa_payload_seen:
            entry["decoded"] = {
                "protocol": "eddystone",
                "frame": "pending",
                "note": "uuid-advertised; payload not yet captured",
                "confidence": "low",
            }
            protocols.append("eddystone_pending")
        if vendor_hint:
            vendors.append(vendor_hint)
        result["service_uuids"].append(entry)

    for ad_raw, val in (advertising_data or {}).items():
        try:
            ad_type = int(ad_raw)
        except (TypeError, ValueError):
            continue
        raw = _to_bytes(val)
        result["advertising_data"].append({
            "ad_type": ad_type,
            "ad_type_hex": f"0x{ad_type:02x}",
            "name": _resolve_ad_type_name(ad_type),
            "raw_hex": raw.hex(),
            "ascii": _ascii(raw),
        })

    result["summary"]["vendors"] = sorted(set(vendors))
    result["summary"]["protocols"] = sorted(set(protocols))
    return result


def format_beacon_summary(dissection: Optional[Mapping[str, Any]]) -> str:
    """Return a compact one-line beacon identity tag for scan/survey output.

    Empty string when no beacon protocols were decoded. Examples::

        [ibeacon_compact m=1/i=169 tx=-59] [feaa-pending]
        [ibeacon m=1/i=2] [eddystone url=https://espressif.com]
    """
    if not dissection:
        return ""
    tags: List[str] = []
    for entry in dissection.get("manufacturer_data") or []:
        decoded = entry.get("decoded") or {}
        proto = decoded.get("protocol")
        if proto in ("ibeacon", "ibeacon_compact"):
            major = decoded.get("major")
            minor = decoded.get("minor")
            tx = decoded.get("tx_power")
            parts = [proto]
            if major is not None and minor is not None:
                parts.append(f"m={major}/i={minor}")
            if tx is not None:
                parts.append(f"tx={tx}")
            tags.append("[" + " ".join(parts) + "]")
    for entry in dissection.get("service_data") or []:
        decoded = entry.get("decoded") or {}
        if decoded.get("protocol") == "eddystone":
            frame = decoded.get("frame")
            if frame == "url" and decoded.get("url"):
                tags.append(f"[eddystone url={decoded['url']}]")
            elif frame:
                tags.append(f"[eddystone {frame}]")
            else:
                tags.append("[eddystone]")
    for entry in dissection.get("service_uuids") or []:
        decoded = entry.get("decoded") or {}
        if decoded.get("frame") == "pending":
            tags.append("[feaa-pending]")
    if not tags:
        protocols = (dissection.get("summary") or {}).get("protocols") or []
        if "eddystone_pending" in protocols:
            tags.append("[feaa-pending]")
        elif "eddystone" in protocols:
            tags.append("[eddystone]")
        elif "ibeacon_compact" in protocols:
            tags.append("[ibeacon_compact]")
        elif "ibeacon" in protocols:
            tags.append("[ibeacon]")
    # Preserve order while de-duplicating
    seen = set()
    ordered: List[str] = []
    for tag in tags:
        if tag not in seen:
            seen.add(tag)
            ordered.append(tag)
    return " ".join(ordered)


# ---------------------------------------------------------------------------
# Persisted-record adapter (shared by CLI ``db show`` and AoI reports)
# ---------------------------------------------------------------------------

def _record_field(record: Mapping[str, Any], key: str) -> Any:
    """Fetch an advertisement field from a flat record or its nested ``device`` row.

    ``get_device_detail()`` nests the ``devices``-table row under ``device`` while
    AoI enrichment dicts carry the same fields at the top level — check both so a
    single caller works for either shape.
    """
    if key in record and record[key] is not None:
        return record[key]
    dev = record.get("device")
    if isinstance(dev, Mapping):
        return dev.get(key)
    return None


def _hex_map_to_bytes(raw: Any) -> Dict[Any, bytes]:
    """Coerce a persisted ``{key: hex-str | byte-list}`` map (or its JSON string
    form) into ``{key: bytes}``. Unparseable entries are skipped, not raised."""
    if isinstance(raw, str):
        try:
            raw = _json.loads(raw)
        except (ValueError, TypeError):
            return {}
    out: Dict[Any, bytes] = {}
    if isinstance(raw, Mapping):
        for k, v in raw.items():
            try:
                out[k] = bytes.fromhex(v) if isinstance(v, str) else _to_bytes(v)
            except (ValueError, TypeError):
                continue
    return out


def dissect_persisted_record(record: Mapping[str, Any]) -> Optional[Dict[str, Any]]:
    """Reconstruct dissector inputs from a persisted device/adv record and dissect.

    Accepts the flat advertisement fields as stored in the ``devices`` table (or
    an AoI enrichment dict): ``manufacturer_id`` + ``manufacturer_data``,
    ``service_data``, ``advertising_data`` and ``uuids``. Values may be ``bytes``
    (SQLite BLOB), hex strings, D-Bus byte lists, or JSON strings — all are
    tolerated. Fields are looked up top-level first, then under a nested
    ``device`` row.

    Returns the :func:`dissect_advertisement` result dict, or ``None`` when the
    record carries no advertisement data. Never raises — enrichment must not
    break its callers.
    """
    try:
        service_data = _hex_map_to_bytes(_record_field(record, "service_data"))
        advertising_data = {
            int(k): v
            for k, v in _hex_map_to_bytes(_record_field(record, "advertising_data")).items()
            if str(k).lstrip("-").isdigit()
        }

        manufacturer_data: Dict[int, bytes] = {}
        mfr_id = _record_field(record, "manufacturer_id")
        mfr_val = _record_field(record, "manufacturer_data")
        if mfr_id is not None and mfr_val is not None:
            try:
                mv = bytes.fromhex(mfr_val) if isinstance(mfr_val, str) else _to_bytes(mfr_val)
                manufacturer_data[int(mfr_id)] = mv
            except (ValueError, TypeError):
                pass

        uuids = _record_field(record, "uuids")
        if isinstance(uuids, str):
            try:
                uuids = _json.loads(uuids)
            except (ValueError, TypeError):
                uuids = []
        if not isinstance(uuids, list):
            uuids = []

        if not (manufacturer_data or service_data or advertising_data or uuids):
            return None

        return dissect_advertisement(
            manufacturer_data=manufacturer_data or None,
            service_data=service_data or None,
            service_uuids=uuids or None,
            advertising_data=advertising_data or None,
        )
    except Exception:  # noqa: BLE001 - enrichment must never break the caller
        return None
