#!/usr/bin/python3

# Auto-generated Class-of-Device tables (SIG core/class_of_device.yaml)
# DO NOT EDIT - run `python -m bleep.bt_ref.update_extra_refs` (or `bleep refresh-refs`).
# Generated: 2026-07-28T09:31:11
# Source: assigned_numbers/core/class_of_device.yaml


COD_SERVICES = {   13: 'Limited Discoverable Mode',
    14: 'LE audio',
    15: 'Reserved for Future Use',
    16: 'Positioning (Location identification)',
    17: 'Networking (LAN, Ad hoc, ...)',
    18: 'Rendering (Printing, Speakers, ...)',
    19: 'Capturing (Scanner, Microphone, ...)',
    20: 'Object Transfer (v-Inbox, v-Folder, ...)',
    21: 'Audio (Speaker, Microphone, Headset service, ...)',
    22: 'Telephony (Cordless telephony, Modem, Headset service, ...)',
    23: 'Information (WEB-server, WAP-server, ...)'}

COD_MAJOR_DEVICE_CLASS = {   0: 'Miscellaneous',
    1: 'Computer (desktop, notebook, PDA, organizer, ...)',
    2: 'Phone (cellular, cordless, pay phone, modem, ...)',
    3: 'LAN/Network Access Point',
    4: 'Audio/Video (headset, speaker, stereo, video display, VCR, ...)',
    5: 'Peripheral (mouse, joystick, keyboard, ...)',
    6: 'Imaging (printer, scanner, camera, display, ...)',
    7: 'Wearable',
    8: 'Toy',
    9: 'Health',
    31: 'Uncategorized (device code not specified)'}

COD_MINOR_DEVICE_CLASS = {   1: {   0: 'Uncategorized (code for device not assigned)',
           1: 'Desktop Workstation',
           2: 'Server-class Computer',
           3: 'Laptop',
           4: 'Handheld PC/PDA (clamshell)',
           5: 'Palm-size PC/PDA',
           6: 'Wearable Computer (watch size)',
           7: 'Tablet'},
    2: {   0: 'Uncategorized (code for device not assigned)',
           1: 'Cellular',
           2: 'Cordless',
           3: 'Smartphone',
           4: 'Wired Modem or Voice Gateway',
           5: 'Common ISDN Access'},
    3: {   0: 'Fully available',
           1: '1% to 17% utilized',
           2: '17% to 33% utilized',
           3: '33% to 50% utilized',
           4: '50% to 67% utilized',
           5: '67% to 83% utilized',
           6: '83% to 99% utilized',
           7: 'No service available'},
    4: {   0: 'Uncategorized (code not assigned)',
           1: 'Wearable Headset Device',
           2: 'Hands-free Device',
           3: 'Reserved for Future Use',
           4: 'Microphone',
           5: 'Loudspeaker',
           6: 'Headphones',
           7: 'Portable Audio',
           8: 'Car Audio',
           9: 'Set-top box',
           10: 'HiFi Audio Device',
           11: 'VCR',
           12: 'Video Camera',
           13: 'Camcorder',
           14: 'Video Monitor',
           15: 'Video Display and Loudspeaker',
           16: 'Video Conferencing',
           17: 'Reserved for Future Use',
           18: 'Gaming/Toy',
           19: 'Hearing Aid',
           20: 'Glasses'},
    5: {   0: 'Uncategorized (code not assigned)',
           1: 'Keyboard',
           2: 'Pointing Device',
           3: 'Combo Keyboard/Pointing Device'},
    7: {   1: 'Wristwatch',
           2: 'Pager',
           3: 'Jacket',
           4: 'Helmet',
           5: 'Glasses',
           6: 'Pin (e.g., lapel pin, broach, badge)'},
    8: {1: 'Robot', 2: 'Vehicle', 3: 'Doll/Action Figure', 4: 'Controller', 5: 'Game'},
    9: {   0: 'Undefined',
           1: 'Blood Pressure Monitor',
           2: 'Thermometer',
           3: 'Weighing Scale',
           4: 'Glucose Meter',
           5: 'Pulse Oximeter',
           6: 'Heart/Pulse Rate Monitor',
           7: 'Health Data Display',
           8: 'Step Counter',
           9: 'Body Composition Analyzer',
           10: 'Peak Flow Monitor',
           11: 'Medication Monitor',
           12: 'Knee Prosthesis',
           13: 'Ankle Prosthesis',
           14: 'Generic Health Manager',
           15: 'Personal Mobility Device'}}

COD_SUBMINOR_DEVICE_CLASS = {   3: {0: 'Uncategorized (use this value if no others apply)'},
    5: {   0: 'Uncategorized (code not assigned)',
           1: 'Joystick',
           2: 'Gamepad',
           3: 'Remote Control',
           4: 'Sensing Device',
           5: 'Digitizer Tablet',
           6: 'Card Reader (e.g., SIM Card Reader)',
           7: 'Digital Pen',
           8: 'Handheld Scanner (e.g., barcodes, RFID)',
           9: 'Handheld Gestural Input Device (e.g., "wand" form factor)'},
    6: {0: 'Uncategorized (default)'}}
