#!/usr/bin/python3

# Auto-generated profile-scoped SDP attribute-ID labels (SIG assigned numbers).
# DO NOT EDIT - run `python -m bleep.bt_ref.update_sig_sdp_attr_ids` (or `bleep refresh-refs`).
# Generated: 2026-07-28T09:31:25
# Source: assigned_numbers/service_discovery/{attribute_ids/*,siblings}.yaml


"""Profile-scoped SDP attribute-ID labels + string offsets + protocol params
(SIG assigned_numbers/service_discovery).

Attribute IDs >= 0x0200 are context-dependent; a label is only correct in the
context of the record's Service-Class-ID. ``SERVICE_CLASS_TO_PROFILE`` maps a
service class to the owning profile so a numeric ID is only ever labelled when
the service class disambiguates it.

``SDP_STRING_ATTR_OFFSETS`` are offsets added to a LanguageBaseAttributeIDList
base (attr 0x0006) for ServiceName/Description/ProviderName in each language.
``SDP_PROTOCOL_PARAMETERS`` names the positional parameters of a
ProtocolDescriptorList (attr 0x0004) per protocol."""
SDP_PROFILE_ATTR_IDS = {   'a2dp': {'0x0311': 'Supported Features'},
    'avrcp': {'0x0311': 'Supported Features'},
    'bip': {   '0x0200': 'GoepL2capPsm (BIP v1.1 and later)',
               '0x0310': 'Supported Capabilities',
               '0x0311': 'Supported Features',
               '0x0312': 'Supported Functions',
               '0x0313': 'Total Imaging Data Capacity'},
    'bpp': {   '0x0350': 'Document Formats Supported',
               '0x0352': 'Character Repertoires Supported',
               '0x0354': 'XHTML-Print Image Formats Supported',
               '0x0356': 'Color Supported',
               '0x0358': '1284ID',
               '0x035a': 'Printer Name',
               '0x035c': 'Printer Location',
               '0x035e': 'Duplex Supported',
               '0x0360': 'Media Types Supported',
               '0x0362': 'MaxMediaWidth',
               '0x0364': 'MaxMediaLength',
               '0x0366': 'Enhanced Layout Supported',
               '0x0368': 'RUI Formats Supported',
               '0x0370': 'Reference Printing RUI Supported',
               '0x0372': 'Direct Printing RUI Supported',
               '0x0374': 'Reference Printing Top URL',
               '0x0376': 'Direct Printing Top URL',
               '0x0378': 'Printer Admin RUI Top URL',
               '0x037a': 'Device Name'},
    'browse_group_descriptor_service': {'0x0200': 'GroupID'},
    'calendar_tasks_and_notes': {'0x0315': 'CTN InstanceID', '0x0317': 'CTN Supported Features'},
    'cordless_telephony_profile': {'0x0301': 'External Network'},
    'device_identification_profile': {   '0x0200': 'SpecificationID',
                                         '0x0201': 'VendorID',
                                         '0x0202': 'ProductID',
                                         '0x0203': 'Version',
                                         '0x0204': 'PrimaryRecord',
                                         '0x0205': 'VendorIDSource'},
    'dun': {'0x0305': 'Audio Feedback Support'},
    'fax_profile': {   '0x0302': 'Fax Class 1 Support',
                       '0x0303': 'Fax Class 2.0 Support',
                       '0x0304': 'Fax Class 2 Support(vendor-specific class)',
                       '0x0305': 'Audio Feedback Support'},
    'file_transfer_profile': {'0x0200': 'GoepL2capPsm (FTP v1.2 and later)'},
    'gnss': {'0x0200': 'SupportedFeatures'},
    'hands_free_profile': {'0x0301': 'Network', '0x0311': 'SupportedFeatures'},
    'hardcopy_replacement_profile': {   '0x0300': '1284ID',
                                        '0x0302': 'Device Name',
                                        '0x0304': 'Friendly Name',
                                        '0x0306': 'Device Location'},
    'headset_profile': {'0x0302': 'Remote Audio Volume Control'},
    'health_device_profile': {   '0x0200': 'Supported Features',
                                 '0x0301': 'Data Exchange Specification',
                                 '0x0302': 'MCAP Supported Procedures'},
    'human_interface_device_profile': {   '0x0200': 'HIDDeviceReleaseNumber (Deprecated in HID '
                                                    '1.1)',
                                          '0x0201': 'HIDParserVersion',
                                          '0x0202': 'HIDDeviceSubclass',
                                          '0x0203': 'HIDCountryCode',
                                          '0x0204': 'HIDVirtualCable',
                                          '0x0205': 'HIDReconnectInitiate',
                                          '0x0206': 'HIDDescriptorList',
                                          '0x0207': 'HIDLANGIDBaseList',
                                          '0x0208': 'HIDSDPDisable (Deprecated in HID 1.1)',
                                          '0x0209': 'HIDBatteryPower',
                                          '0x020a': 'HIDRemoteWake',
                                          '0x020b': 'HIDProfileVersion',
                                          '0x020c': 'HIDSupervisionTimeout',
                                          '0x020d': 'HIDNormallyConnectable',
                                          '0x020e': 'HIDBootDevice',
                                          '0x020f': 'HIDSSRHostMaxLatency',
                                          '0x0210': 'HIDSSRHostMinTimeout'},
    'interoperability_requirements': {   '0x0306': 'NetworkAddress',
                                         '0x0307': 'WAPGateway',
                                         '0x0308': 'HomePageURL',
                                         '0x0309': 'WAPStackType'},
    'message_access_profile': {   '0x0200': 'GoepL2capPsm (MAP v1.2 and later)',
                                  '0x0315': 'MASInstanceID',
                                  '0x0316': 'SupportedMessageTypes',
                                  '0x0317': 'MapSupportedFeatures (MAP v1.2 and later)'},
    'multi_profile': {   '0x0200': 'Supported Scenarios MPSD',
                         '0x0201': 'Supported Scenarios MPMD',
                         '0x0202': 'Supported Profile and Protocol Dependecies'},
    'object_push_profile': {   '0x0200': 'GoepL2capPsm (OPP v1.2 and later)',
                               '0x0300': 'Service Version',
                               '0x0303': 'Supported Formats List'},
    'pan_profile': {   '0x0200': 'IpSubnet (Not used in PAN v1.0)',
                       '0x030a': 'Security Description',
                       '0x030b': 'NetAccessType',
                       '0x030c': 'MaxNetAccessRate',
                       '0x030d': 'IPv4Subnet',
                       '0x030e': 'IPv6Subnet'},
    'phone_book_access_profile': {   '0x0200': 'GoepL2capPsm (PBAP v1.2 and later)',
                                     '0x0314': 'Supported Repositories',
                                     '0x0317': 'PbapSupportedFeatures (PBAP v1.2 and later)'},
    'synchronization_profile': {'0x0301': 'Supported Data Stores List'}}

SERVICE_CLASS_TO_PROFILE = {   '0x1001': 'browse_group_descriptor_service',
    '0x1103': 'dun',
    '0x1104': 'synchronization_profile',
    '0x1105': 'object_push_profile',
    '0x1106': 'file_transfer_profile',
    '0x1107': 'synchronization_profile',
    '0x1108': 'headset_profile',
    '0x1109': 'cordless_telephony_profile',
    '0x110a': 'a2dp',
    '0x110b': 'a2dp',
    '0x110c': 'avrcp',
    '0x110d': 'a2dp',
    '0x110e': 'avrcp',
    '0x110f': 'avrcp',
    '0x1111': 'fax_profile',
    '0x1112': 'headset_profile',
    '0x1113': 'interoperability_requirements',
    '0x1114': 'interoperability_requirements',
    '0x1115': 'pan_profile',
    '0x1116': 'pan_profile',
    '0x1117': 'pan_profile',
    '0x1118': 'bpp',
    '0x1119': 'bpp',
    '0x111a': 'bip',
    '0x111b': 'bip',
    '0x111c': 'bip',
    '0x111d': 'bip',
    '0x111e': 'hands_free_profile',
    '0x111f': 'hands_free_profile',
    '0x1120': 'bpp',
    '0x1122': 'bpp',
    '0x1123': 'bpp',
    '0x1124': 'human_interface_device_profile',
    '0x1125': 'hardcopy_replacement_profile',
    '0x1126': 'hardcopy_replacement_profile',
    '0x1127': 'hardcopy_replacement_profile',
    '0x112e': 'phone_book_access_profile',
    '0x112f': 'phone_book_access_profile',
    '0x1130': 'phone_book_access_profile',
    '0x1131': 'headset_profile',
    '0x1132': 'message_access_profile',
    '0x1133': 'message_access_profile',
    '0x1134': 'message_access_profile',
    '0x1135': 'gnss',
    '0x1136': 'gnss',
    '0x113a': 'multi_profile',
    '0x113b': 'multi_profile',
    '0x113c': 'calendar_tasks_and_notes',
    '0x113d': 'calendar_tasks_and_notes',
    '0x113e': 'calendar_tasks_and_notes',
    '0x1200': 'device_identification_profile',
    '0x1400': 'health_device_profile',
    '0x1401': 'health_device_profile',
    '0x1402': 'health_device_profile'}

SDP_STRING_ATTR_OFFSETS = {'0x0000': 'ServiceName', '0x0001': 'ServiceDescription', '0x0002': 'ProviderName'}

SDP_PROTOCOL_PARAMETERS = {   'BNEP': {1: 'Version', 2: 'Supported Network Packet Type List'},
    'L2CAP': {1: 'PSM'},
    'RFCOMM': {1: 'Channel'},
    'TCP': {1: 'Port'},
    'UDP': {1: 'Port'}}
