#!/usr/bin/python3
"""Generator for BlueZ-sourced reference tables (SDP universal attribute IDs).

Unlike :mod:`bleep.bt_ref.update_ble_uuids` / :mod:`bleep.bt_ref.update_extra_refs`
(which pull YAML from the Bluetooth SIG *assigned_numbers* repo), the SDP
*attribute-ID* labels are not published as a single machine-readable SIG file —
the SIG ``service_discovery/attribute_ids/`` tree is a directory of many
per-profile YAMLs. The canonical, stable, machine-parseable source for the
**universal** SDP attribute IDs is instead the upstream BlueZ header
``lib/sdp.h`` (``#define SDP_ATTR_*``), mirrored at:

    https://github.com/bluez/bluez.git   (canonical: git://git.kernel.org/pub/scm/bluetooth/bluez.git)

Design mirrors the SIG updaters: **network-best-effort with a committed cache
fallback** (``bt_ref/bluez_cache/sdp.h``), so the package stays self-contained
and offline-safe. A failed fetch (and no cache) leaves the previously committed
module untouched — it never zeroes a table.

Scope — universal range only (``0x0000``–``0x000D``) plus the primary-language
string trio (``0x0100``–``0x0102``). Attribute IDs ``>= 0x0200`` are
**context-dependent**: BlueZ deliberately reuses e.g. ``0x0200`` for
``GROUP_ID`` / ``IP_SUBNET`` / ``VERSION_NUM_LIST`` / ``SPECIFICATION_ID`` /
``HID_DEVICE_RELEASE_NUMBER``, so a single ``{id: name}`` label is only correct
for the universal range. Profile-specific labelling would require joining the
attribute ID to the record's service-class UUID and is intentionally out of
scope here. See ``docs/uuid_translation.md`` (BlueZ-sourced SDP attribute-ID labels).

Usage:
    python -m bleep.bt_ref.update_bluez_refs      # regenerate sdp_attr_ids.py
"""
from __future__ import annotations

import pprint
import re
from datetime import datetime
from pathlib import Path

from bleep.bt_ref.update_ble_uuids import _download_file

_HERE = Path(__file__).parent
_CACHE_DIR = _HERE / "bluez_cache"
_CACHE_DIR.mkdir(exist_ok=True)
_SDP_H_CACHE = _CACHE_DIR / "sdp.h"
_OUT = _HERE / "sdp_attr_ids.py"

# Pinned to a specific upstream commit for reproducible pulls (bump deliberately).
_BLUEZ_PIN = "4c431e5dae3e7cee4ce3d0720fefc530a2524e0b"
_BLUEZ_RAW = f"https://raw.githubusercontent.com/bluez/bluez/{_BLUEZ_PIN}/lib/sdp.h"

# Canonical Bluetooth Core Specification attribute names keyed by the BlueZ
# macro suffix (after the ``SDP_ATTR_`` prefix). The *IDs* are pulled/validated
# from the header; these attach the spec's human-readable English names (BlueZ's
# own hcidump SDP parser keeps an equivalent curated string table). Any macro not
# listed here falls back to a humanised form of its suffix, so a newly added
# universal attribute still emits (just less prettily).
_VERBOSE_NAMES = {
    "RECORD_HANDLE": "Service Record Handle",
    "SVCLASS_ID_LIST": "Service Class ID List",
    "RECORD_STATE": "Service Record State",
    "SERVICE_ID": "Service ID",
    "PROTO_DESC_LIST": "Protocol Descriptor List",
    "BROWSE_GRP_LIST": "Browse Group List",
    "LANG_BASE_ATTR_ID_LIST": "Language Base Attribute ID List",
    "SVCINFO_TTL": "Service Info Time To Live",
    "SERVICE_AVAILABILITY": "Service Availability",
    "PFILE_DESC_LIST": "Bluetooth Profile Descriptor List",
    "DOC_URL": "Documentation URL",
    "CLNT_EXEC_URL": "Client Executable URL",
    "ICON_URL": "Icon URL",
    "ADD_PROTO_DESC_LIST": "Additional Protocol Descriptor Lists",
    "SVCNAME_PRIMARY": "Service Name",
    "SVCDESC_PRIMARY": "Service Description",
    "PROVNAME_PRIMARY": "Provider Name",
}

# ``#define SDP_ATTR_<NAME>\t0x00NN`` — plain hex value (universal range).
_DEF_RE = re.compile(r"^#define\s+SDP_ATTR_(\w+)\s+0x([0-9a-fA-F]{4})\s*$", re.MULTILINE)
# Primary-language string offsets: ``#define SDP_ATTR_<NAME>\t0xNNNN + SDP_PRIMARY_LANG_BASE``.
_LANG_BASE_RE = re.compile(r"^#define\s+SDP_PRIMARY_LANG_BASE\s+0x([0-9a-fA-F]{4})\s*$", re.MULTILINE)
_LANG_OFF_RE = re.compile(
    r"^#define\s+SDP_ATTR_(\w+)\s+0x([0-9a-fA-F]{4})\s*\+\s*SDP_PRIMARY_LANG_BASE\s*$",
    re.MULTILINE,
)

_HDR = (
    "#!/usr/bin/python3\n\n"
    "# Auto-generated SDP universal attribute-ID labels.\n"
    "# DO NOT EDIT - run `python -m bleep.bt_ref.update_bluez_refs` (or `bleep refresh-refs`).\n"
    "# Generated: {ts}\n"
    "# Source: bluez lib/sdp.h @ {pin} ({src})\n\n"
)


def _humanise(suffix: str) -> str:
    """Fallback name for a macro suffix not in the curated table."""
    return suffix.replace("_", " ").title()


# Emitted verbatim into ``sdp_attr_ids.py``. The resolver is universal-first; a
# profile-specific label (IDs >= 0x0200) is only returned when the caller supplies
# the record's Service-Class-ID and it maps to a profile whose SIG attribute table
# (``sdp_profile_attr_ids.py``, generated by ``update_sig_sdp_attr_ids``) knows the
# ID. The profile module is imported defensively so ``sdp_attr_ids`` stays usable
# even if the profile table was never generated.
_RESOLVER_SRC = '''def _service_class_key(service_class_uuid):
    """Normalise a Service-Class-ID to a lowercase 16-bit hex key ("0xnnnn")."""
    if service_class_uuid is None:
        return None
    if isinstance(service_class_uuid, int):
        return f"0x{service_class_uuid & 0xFFFF:04x}"
    s = str(service_class_uuid).strip().lower().replace("0x", "").replace("-", "")
    if len(s) >= 32 and s.endswith("00001000800000805f9b34fb"):
        s = s[4:8]  # 16-bit portion of a SIG-base 128-bit UUID
    try:
        return f"0x{int(s, 16) & 0xFFFF:04x}"
    except ValueError:
        return None


def resolve_sdp_attr_id(attr_id, service_class_uuid=None):
    """Return an SDP attribute-ID label, or None if unknown/ambiguous.

    ``attr_id`` may be an int (0x0004) or a hex string ("0x0004"/"0004").

    The universal range (0x0000-0x000D, plus the primary-language string offsets)
    is always resolved. Profile-context IDs (>= 0x0200) are only resolved when
    ``service_class_uuid`` is supplied *and* maps to a profile whose SIG attribute
    table knows the ID — otherwise None (a numeric ID like 0x0200 means different
    things per profile, so it is never guessed)."""
    if isinstance(attr_id, str):
        s = attr_id.strip().lower().replace("0x", "")
        try:
            attr_id = int(s, 16)
        except ValueError:
            return None
    key = f"0x{attr_id:04x}"
    universal = SDP_UNIVERSAL_ATTR_IDS.get(key)
    if universal is not None:
        return universal
    sc_key = _service_class_key(service_class_uuid)
    if sc_key is None:
        return None
    try:
        from bleep.bt_ref.sdp_profile_attr_ids import (
            SDP_PROFILE_ATTR_IDS,
            SERVICE_CLASS_TO_PROFILE,
        )
    except Exception:
        return None
    profile = SERVICE_CLASS_TO_PROFILE.get(sc_key)
    if not profile:
        return None
    return SDP_PROFILE_ATTR_IDS.get(profile, {}).get(key)
'''


def _fetch_sdp_h() -> str | None:
    """Fetch ``lib/sdp.h`` (network-best-effort → committed cache fallback)."""
    print(f"[*] Fetching BlueZ lib/sdp.h: {_BLUEZ_RAW}")
    data = _download_file(_BLUEZ_RAW)
    if data:
        try:
            _SDP_H_CACHE.write_text(data, encoding="utf-8")
            print(f"[+] Cached sdp.h to {_SDP_H_CACHE}")
        except Exception as e:  # pragma: no cover - defensive
            print(f"[!] Failed to cache sdp.h: {e}")
        return data
    print("[*] Falling back to committed cache for sdp.h")
    if _SDP_H_CACHE.exists():
        return _SDP_H_CACHE.read_text(encoding="utf-8")
    print("[!] No committed sdp.h cache found")
    return None


def _compile_universal(header: str) -> dict[str, str]:
    """Parse the universal-range (0x0000–0x000D) + primary-language attr IDs.

    Returns ``{"0x00NN": "Verbose Name"}``. Only IDs ``<= 0x000D`` from the plain
    ``#define`` set are accepted so context-dependent (``>= 0x0200``) IDs never
    receive an ambiguous single label.
    """
    out: dict[str, str] = {}
    for m in _DEF_RE.finditer(header):
        suffix, hexval = m.group(1), m.group(2)
        val = int(hexval, 16)
        if val > 0x000D:
            continue  # universal range only; profile-specific IDs are ambiguous
        name = _VERBOSE_NAMES.get(suffix) or _humanise(suffix)
        out[f"0x{val:04x}"] = name

    lang_base_m = _LANG_BASE_RE.search(header)
    if lang_base_m:
        base = int(lang_base_m.group(1), 16)
        for m in _LANG_OFF_RE.finditer(header):
            suffix, hexoff = m.group(1), m.group(2)
            val = base + int(hexoff, 16)
            name = _VERBOSE_NAMES.get(suffix) or _humanise(suffix)
            out[f"0x{val:04x}"] = name
    return out


def _emit(table: dict[str, str]) -> None:
    body = [_HDR.format(ts=datetime.now().isoformat(timespec="seconds"), pin=_BLUEZ_PIN, src="lib/sdp.h")]
    body.append(
        '"""SDP universal attribute-ID labels (BlueZ lib/sdp.h, universal range).\n\n'
        "Only the universal SDP attribute IDs (0x0000-0x000D) plus the primary-language\n"
        "string offsets (0x0100-0x0102) carry an unambiguous single label and live in\n"
        "``SDP_UNIVERSAL_ATTR_IDS``. IDs >= 0x0200 are profile-context-dependent, so they\n"
        "are absent from that table; ``resolve_sdp_attr_id(attr_id, service_class_uuid)``\n"
        "resolves them via the per-profile SIG tables in ``sdp_profile_attr_ids.py`` only\n"
        'when the record\'s service class disambiguates them."""\n'
    )
    body.append("SDP_UNIVERSAL_ATTR_IDS = " + pprint.pformat(table, indent=4, width=100, sort_dicts=True))
    body.append("")
    body.append(_RESOLVER_SRC)
    _OUT.write_text("\n".join(body), encoding="utf-8")


def regenerate() -> None:
    """Regenerate ``sdp_attr_ids.py`` (non-destructive on failure)."""
    header = _fetch_sdp_h()
    if not header:
        print("[!] BlueZ sdp.h unavailable; leaving sdp_attr_ids.py untouched")
        return
    table = _compile_universal(header)
    if not table:
        print("[!] No SDP attribute IDs parsed; leaving sdp_attr_ids.py untouched")
        return
    _emit(table)
    print(f"[+] Wrote {_OUT.name} ({len(table)} universal attribute IDs)")


if __name__ == "__main__":
    regenerate()
