#!/usr/bin/python3

# Auto-generated vendor/community advertisement specs (device-library).
# DO NOT EDIT - run `python -m bleep.bt_ref.update_vendor_specs` instead.
# Generated: 2026-07-24T05:35:33
# Source: github:BLESPloit/device-library@main
# Spec count: 37


SERVICE_DATA_UUID16 = {   'fcc0': 'Google Nearby',
    'fcf1': 'Google Nearby',
    'fd69': 'Samsung',
    'fe2c': 'Google Fast Pair',
    'fe9f': 'Google Nearby',
    'feaa': 'Eddystone',
    'fef3': 'Google Nearby'}

SERVICE_UUID16 = {   '1122': 'Tesla',
    '1580': 'Swapfiets bike',
    '3081': 'Flipper Zero',
    '3082': 'Flipper Zero',
    '3083': 'Flipper Zero'}

SERVICE_UUID128 = {   '5b833e05-6bc7-4802-8e9a-723ceca4bd8f': 'Sony',
    '5b833e20-6bc7-4802-8e9a-723ceca4bd8f': 'Sony',
    '5b833e26-6bc7-4802-8e9a-723ceca4bd8f': 'Sony',
    '5b833e28-6bc7-4802-8e9a-723ceca4bd8f': 'Sony',
    'a6ed0401d344460a8075b9e8ec90d71b': 'Oclean smart toothbrush'}

COMPANY_ID = {   '0006': ['Microsoft Nearby'],
    '004c': ['Apple Continuity (dispatcher)', 'iBeacon'],
    '006b': ['Polar'],
    '0075': ['Samsung'],
    '0087': ['Garmin'],
    '00c4': ['LG'],
    '011b': ['HPE Aruba Access Point'],
    '012d': ['Sony'],
    '020f': ['Swapfiets bike'],
    '0223': ['IQOS'],
    '027d': ['Huawei'],
    '038f': ['Xiaomi'],
    '05a7': ['Sonos'],
    '072f': ['Oneplus'],
    'bad0': ['OrangeCon 2026 Badge']}

MANUFACTURER_PREFIX = [   {'company_id': '004c', 'prefix': '0215', 'name': 'iBeacon', 'priority': 40},
    {'company_id': '011b', 'prefix': '08', 'name': 'HPE Aruba Access Point', 'priority': 45}]

SPECS = [   {   'name': 'Device type from appearance and services',
        'path': 'generic/device_type_meta/manifest.json',
        'priority': 10,
        'conditions': {'has_gap_device_type_hints': True}},
    {   'name': 'Apple Continuity (dispatcher)',
        'path': 'vendors/apple/apple_dispatcher/manifest.json',
        'priority': 20,
        'conditions': {'company_id': '004C'}},
    {   'name': 'Flipper Zero',
        'path': 'vendors/flipper_zero/manifest.json',
        'priority': 20,
        'conditions': {'service_uuid_16': ['3081', '3082', '3083']}},
    {   'name': 'Garmin',
        'path': 'vendors/garmin/manifest.json',
        'priority': 20,
        'conditions': {'company_id': '0087'}},
    {   'name': 'Google Nearby',
        'path': 'vendors/google_nearby/manifest.json',
        'priority': 20,
        'conditions': {'service_data_uuid_16': ['fcf1', 'fe9f', 'fef3', 'fcc0']}},
    {   'name': 'Huawei',
        'path': 'vendors/huawei/manifest.json',
        'priority': 20,
        'conditions': {'company_id': '027D', 'device_name_contains': 'HUAWEI'}},
    {   'name': 'IQOS',
        'path': 'vendors/iqos/manifest.json',
        'priority': 20,
        'conditions': {'company_id': '0223'}},
    {   'name': 'Jabra',
        'path': 'vendors/jabra/manifest.json',
        'priority': 20,
        'conditions': {'device_name_contains': 'Jabra'}},
    {   'name': 'LG',
        'path': 'vendors/lg/manifest.json',
        'priority': 20,
        'conditions': {'company_id': '00C4'}},
    {   'name': 'Oneplus',
        'path': 'vendors/oneplus/manifest.json',
        'priority': 20,
        'conditions': {'company_id': '072F'}},
    {   'name': 'OrangeCon 2026 Badge',
        'path': 'products/orangecon_2026_badge/manifest.json',
        'priority': 20,
        'conditions': {'company_id': 'BAD0', 'device_name_contains': 'OCB'}},
    {   'name': 'Polar',
        'path': 'vendors/polar/manifest.json',
        'priority': 20,
        'conditions': {'company_id': '006b', 'device_name_contains': 'Polar'}},
    {   'name': 'Sonos',
        'path': 'vendors/sonos/manifest.json',
        'priority': 20,
        'conditions': {'company_id': '05A7'}},
    {   'name': 'Sony',
        'path': 'vendors/sony/manifest.json',
        'priority': 20,
        'conditions': {   'one_of': [   {'company_id': '012D'},
                                        {   'service_uuid_128': '5b833e05-6bc7-4802-8e9a-723ceca4bd8f'},
                                        {   'service_uuid_128': '5b833e26-6bc7-4802-8e9a-723ceca4bd8f'},
                                        {   'service_uuid_128': '5b833e28-6bc7-4802-8e9a-723ceca4bd8f'},
                                        {   'service_uuid_128': '5b833e20-6bc7-4802-8e9a-723ceca4bd8f'}]}},
    {   'name': 'Xiaomi',
        'path': 'vendors/xiaomi/manifest.json',
        'priority': 20,
        'conditions': {'company_id': '038F'}},
    {   'name': 'Google Fast Pair',
        'path': 'protocols/fast_pair/manifest.json',
        'priority': 25,
        'conditions': {'service_data_uuid_16': 'fe2c'}},
    {   'name': 'Samsung',
        'path': 'vendors/samsung/manifest.json',
        'priority': 25,
        'conditions': {'one_of': [{'company_id': '0075'}, {'service_data_uuid_16': 'fd69'}]}},
    {   'name': 'Apple Find My',
        'path': 'vendors/apple/apple_findmy/manifest.json',
        'priority': 30,
        'conditions': {   'fingerprint_has_entry_id': 'apple_meta',
                          'fingerprint_entry_attributes': {'continuity_has_findmy': 'true'}}},
    {   'name': 'Apple Handoff',
        'path': 'vendors/apple/apple_handoff/manifest.json',
        'priority': 30,
        'conditions': {   'fingerprint_has_entry_id': 'apple_meta',
                          'fingerprint_entry_attributes': {'continuity_has_handoff': 'true'}}},
    {   'name': 'Apple Nearby Action',
        'path': 'vendors/apple/apple_nearby_action/manifest.json',
        'priority': 30,
        'conditions': {   'fingerprint_has_entry_id': 'apple_meta',
                          'fingerprint_entry_attributes': {'continuity_has_nearbyaction': 'true'}}},
    {   'name': 'Apple Nearby Info',
        'path': 'vendors/apple/apple_nearby_info/manifest.json',
        'priority': 30,
        'conditions': {   'fingerprint_has_entry_id': 'apple_meta',
                          'fingerprint_entry_attributes': {'continuity_has_nearbyinfo': 'true'}}},
    {   'name': 'Apple Proximity Pairing',
        'path': 'vendors/apple/apple_proximity/manifest.json',
        'priority': 30,
        'conditions': {   'fingerprint_has_entry_id': 'apple_meta',
                          'fingerprint_entry_attributes': {'continuity_has_proximity': 'true'}}},
    {   'name': 'iBeacon',
        'path': 'protocols/ibeacon/manifest.json',
        'priority': 40,
        'conditions': {'company_id': '004C', 'manufacturer_data_prefix_hex': '0215'}},
    {   'name': 'Eddystone',
        'path': 'protocols/eddystone/manifest.json',
        'priority': 45,
        'conditions': {'service_data_uuid_16': 'feaa'}},
    {   'name': 'HPE Aruba Access Point',
        'path': 'vendors/aruba/manifest.json',
        'priority': 45,
        'conditions': {   'one_of': [   {   'company_id': '011B',
                                            'manufacturer_data_prefix_hex': '08'},
                                        {   'fingerprint_has_entry_id': 'ibeacon',
                                            'fingerprint_entry_attributes': {   'uuid': '4152554e-f99b-4a3b-86d0-947070693a78'}},
                                        {'device_name_regex': '^(?i)AP-[0-9a-f]{12}$'}]}},
    {   'name': 'Lime Scooters',
        'path': 'vendors/lime/manifest.json',
        'priority': 45,
        'conditions': {'device_name_regex': '^lime-[0-9]+$'}},
    {   'name': 'Tesla',
        'path': 'vendors/tesla/manifest.json',
        'priority': 45,
        'conditions': {   'one_of': [   {'fingerprint_has_entry_id': 'ibeacon'},
                                        {   'device_name_regex': '^S.{17}$',
                                            'service_uuid_16': '1122'}]}},
    {   'name': 'BLESPlo.it Light',
        'path': 'products/blesploit_lightbulb/manifest.json',
        'priority': 50,
        'conditions': {'service_data_uuid_128': 'a700cc65-e486-40ba-5d24-99601dc38fd7'}},
    {   'name': 'Google Pixel Buds 2a',
        'path': 'products/pixel_buds_2a/manifest.json',
        'priority': 50,
        'conditions': {'device_name_contains': 'Pixel Buds 2a'}},
    {   'name': 'Happy Lighting',
        'path': 'products/happy_lighting/manifest.json',
        'priority': 50,
        'conditions': {   'device_name_regex': '^(Triones|BRGlight|Color\\+|Dream-|Light-|Color-|QHM|Flash|LD-|Dimmer|Dream\\*|Dream#|Dream~|Dream&|Morimoto|Thaillamp|LXDZ|Archaic|GLOWDRIV|RAMAND|Dream=|QLAMP)'}},
    {   'name': 'Oclean smart toothbrush',
        'path': 'products/oclean_toothbrush/manifest.json',
        'priority': 50,
        'conditions': {   'one_of': [   {'device_name_contains': 'Oclean'},
                                        {'service_uuid_128': 'a6ed0401d344460a8075b9e8ec90d71b'}]}},
    {   'name': 'Rapidpower robotic dog',
        'path': 'products/rapidpower_robotic_dog/manifest.json',
        'priority': 50,
        'conditions': {'device_name_contains': 'Rapidpower-dog'}},
    {   'name': 'Realov vibe',
        'path': 'products/realov_vibe/manifest.json',
        'priority': 50,
        'conditions': {'device_name_contains': 'REALOV_VIBE'}},
    {   'name': 'Shell SuperCars',
        'path': 'products/shell_supercars/manifest.json',
        'priority': 50,
        'conditions': {'device_name_regex': '^QCAR-[0-9A-F]{4}$'}},
    {   'name': 'Sony WH-CH720N',
        'path': 'products/sony_wh_ch720n/manifest.json',
        'priority': 50,
        'conditions': {'device_name_contains': ['WH-CH720N', 'LE-WH-CH720N']}},
    {   'name': 'Swapfiets bike',
        'path': 'vendors/swapfiets/manifest.json',
        'priority': 50,
        'conditions': {   'company_id': '020f',
                          'service_uuid_16': '1580',
                          'device_name_regex': '^Swapfiets$'}},
    {   'name': 'Microsoft Nearby',
        'path': 'vendors/microsoft_nearby/manifest.json',
        'priority': 100,
        'conditions': {'company_id': '0006'}}]
